# modifiers for markov .in files generated by rSOILWAT2

# adjust mkv_covar.in -----------------------------------------------------

#' adjust weekly correction temp correction factors
#'
#' @param covar_in dataframe of weekly temp datagenerated by
#'     rSOILWAT2::dbW_weatherData_to_dataframe
#' @param data dataframe of daily temp and precip
#' @param mean_mult multiplier that mean precipitation event size is to
#' be multiplied by
#'
#' @return dataframe with same columns as covar_in, except the CF have been
#' adjusted (if mean_mult not 1)
#' @export
#'
#' @examples
#' data <-data.frame(rSOILWAT2::dbW_weatherData_to_dataframe(rSOILWAT2::weatherData))
#' covar_in <- rSOILWAT2::dbW_estimate_WGen_coefs(data)[[1]]
#' head(adjust_covar_in(covar_in, data))
#' head(adjust_covar_in(covar_in, data, mean_mult = 2))
adjust_covar_in <- function(covar_in, data, mean_mult = 1) {
  stopifnot(is.data.frame(covar_in),
            is.data.frame(data),
            # can't have NAs
            all(!is.na(data$Tmax_C)),
            all(!is.na(data$Tmin_C)))


  # creating hypothetical new mean temps to use to adjust the correction factors
  wk_smry <- wk_summary_wgen(data, mean_mult = mean_mult)

  # adjust correction factors so that mean temp stays the same when
  # the number of dry days changes
  out <- covar_in
  out$CF_Tmax_dry <- wk_smry$Tmax_dry - wk_smry$Tmax_new
  out$CF_Tmin_dry <- wk_smry$Tmin_dry - wk_smry$Tmin_new
  out$CF_Tmax_wet <- wk_smry$Tmax_wet - wk_smry$Tmax_new
  out$CF_Tmin_wet <- wk_smry$Tmin_wet - wk_smry$Tmin_new
  out
}


# adjust mkv_prob.in ------------------------------------------------------

#' adjust prob.in markov file to increase mean event size
#'
#' @param prob_in prob.in file from rSOILWAT2
#' @param mean_mult how much mean event size should be multiplied by
#' @param adjust_sd logical, whether to adjust the PPT_sd for a give DOY.
#' This option is used so that a draw from a normal distribution with a new
#' (larger) mean is no more/less likely draw a negative value
#'
#' @return prob_in file with frequency and mean event size adjusted
#' to maintain same total precipitation
#'
#' @export
#'
#' @examples
#' data <-data.frame(rSOILWAT2::dbW_weatherData_to_dataframe(rSOILWAT2::weatherData))
#' prob_in <- rSOILWAT2::dbW_estimate_WGen_coefs(data)[[2]]
#' adjust_prob_in(prob_in, mean_mult = 2)
adjust_prob_in <- function(prob_in, mean_mult = 1, adjust_sd = FALSE) {
  stopifnot(is.data.frame(prob_in))

  out <- prob_in
  # reducing probabilities of ppt
  out$p_W_W <- out$p_W_W/mean_mult
  out$p_W_D <- out$p_W_D/mean_mult

  # increasing mean event size
  out$PPT_avg <- out$PPT_avg*mean_mult

  if (adjust_sd) {
    # adjusting sd to account for the fact that annual ppt totals increase
    # when you increase the standard deviation (for a fix mean), because negative
    # draws are replaced with zero. This is my attempt to keep the expected value
    # of the turncated normal distribution

    # here using un-adjusted mean
    z_vec <- (0 - prob_in$PPT_avg)/prob_in$PPT_sd # z score of 0 value
    z_vec[!is.finite(z_vec)] <- NA

    # here using new adjusted mean
    out$PPT_sd <- (0-out$PPT_avg)/z_vec

    # in case above calculate led to NAs, replace with original sd
    out$PPT_sd[is.na(out$PPT_sd) | !is.finite(out$PPT_sd)] <- prob_in$PPT_sd
  }
  out
}

#' adjust the two elements of the list for the markov wx generator
#'
#' @description The purpose of this function is to adjust the wgen input files
#' so that simulated weather has an increased mean event size,
#' decreased ppt frequency, and no change in mean temperature. Also no change
#' in total precipitation
#'
#' @param mkv_in list created by rSOILWAT2::dbW_estimate_WGen_coefs
#' @param data  daily wather data (dataframe)
#' @param mean_mult what to multiply mean event sizes by
#' @param adjust_sd logical, whether to adjust the PPT_sd for a give DOY.
#' This option is used so that a draw from a normal distribution with a new
#' (larger) mean is no more/less likely draw a negative value
#'
#' @return a list with same elements as
#' @export
#'
#' @examples
#' data <-data.frame(rSOILWAT2::dbW_weatherData_to_dataframe(rSOILWAT2::weatherData))
#' mkv_in <- rSOILWAT2::dbW_estimate_WGen_coefs(data)
adjust_mkv_in <- function(mkv_in, data, mean_mult = 1, adjust_sd = FALSE) {
  stopifnot(
    is.list(mkv_in),
    names(mkv_in) == c("mkv_woy", "mkv_doy"),
    is.data.frame(data)
  )

  out <- mkv_in

  # adjust temperature, to keep mean the same when fewer dry days
  out$mkv_woy <- adjust_covar_in(covar_in = mkv_in$mkv_woy,
                                 data = data,
                                 mean_mult = mean_mult)

   # adjust mean event size and frequency
  out$mkv_doy <- adjust_prob_in(prob_in = mkv_in$mkv_doy,
                                mean_mult = mean_mult,
                                adjust_sd = adjust_sd)

  out
}


